

<%@page import="java.time.LocalDate"%>
<%@page import="java.time.format.DateTimeFormatter"%>
<%@page import="Database.ConnectionManager"%>
<%@page import="java.text.SimpleDateFormat"%>
<%@page import="java.sql.*"%>
<%@page import="java.util.Date"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <title>Booking Flights</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    </head>
    <body style = "background-image: url('images\\runway.jpg'); background-size: 100% 100%; background-repeat: no-repeat">


        <%

           Connection con = ConnectionManager.getConnection();
           
           //create statement for table creation
            // PreparedStatement statement = con.prepareStatement("CREATE TABLE FLIGHTS (ID INT AUTO_INCREMENT, FIRSTNAME VARCHAR(25), LASTNAME VARCHAR(25), DEPARTURE_CITY VARCHAR(50), ARRIVAL_CITY VARCHAR(50), DEP_DATE DATE, ARR_DATE DATE, classes varchar(50), checkIn varchar(50), PRIMARY KEY(ID))");
            // statement.execute();
           
            int i = -1;
            String fname = "";
            String lname = "";
            String depcity = "";
            String arrcity = "";
            LocalDate Dpdate=LocalDate.now(); //delaring local date variable 
            long millis = System.currentTimeMillis(); // getting current time
            java.sql.Date depdate = new java.sql.Date(millis); // sql dtatype variable with current time
            java.sql.Date arrdate = new java.sql.Date(millis);
            String classes = "";
            int id=0;

            //if the request comes from the roundtrip form
            if (request.getParameter("btn2") != null) {
                fname = request.getParameter("fname");
                lname = request.getParameter("lname");
                depcity = request.getParameter("depCity");
                arrcity = request.getParameter("arrCity");
                //string date formatter
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                //change it to local date
                Dpdate = LocalDate.parse(request.getParameter("departure"), formatter);
                // then to sql date
                depdate = java.sql.Date.valueOf(Dpdate);
                LocalDate ardate = LocalDate.parse(request.getParameter("return"), formatter);
                arrdate = java.sql.Date.valueOf(ardate);
                classes = request.getParameter("class");

                // insert info to the flights table
                PreparedStatement stm = con.prepareStatement("INSERT INTO FLIGHTS (FIRSTNAME, LASTNAME, DEPARTURE_CITY, "
                        + "ARRIVAL_CITY,DEP_DATE, ARR_DATE, classes) values (?,?,?,?,?,?,?)");

                stm.setString(1, fname);
                stm.setString(2, lname);
                stm.setString(3, depcity);
                stm.setString(4, arrcity);
                stm.setDate(5, depdate);
                stm.setDate(6, arrdate);
                stm.setString(7, classes);
                i = stm.executeUpdate(); 
                
                //getting the ID autogenerated just know for user reference
               PreparedStatement stm1 = con.prepareStatement("SELECT MAX(ID) FROM flights ");
                ResultSet rs = stm1.executeQuery(); 
                rs.next();
                id =rs.getInt(1);

            }
            
            //if the request comes from the oneway form
          else if (request.getParameter("btn1") != null) {
                fname = request.getParameter("fname");
                lname = request.getParameter("lname");
                depcity = request.getParameter("depCity");
                arrcity = request.getParameter("arrCity");
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                Dpdate = LocalDate.parse(request.getParameter("departure"), formatter);
                depdate = java.sql.Date.valueOf(Dpdate);
                classes = request.getParameter("class");
                
                
                PreparedStatement stm = con.prepareStatement("INSERT INTO FLIGHTS (FIRSTNAME, LASTNAME, "
                        + "DEPARTURE_CITY, ARRIVAL_CITY,DEP_DATE, classes) values (?,?,?,?,?,?)");

                stm.setString(1, fname);
                stm.setString(2, lname);
                stm.setString(3, depcity);
                stm.setString(4, arrcity);
                stm.setDate(5, depdate);
                stm.setString(6, classes);
                i = stm.executeUpdate(); 
                PreparedStatement stm1 = con.prepareStatement("SELECT MAX(ID) FROM flights ");
                ResultSet rs = stm1.executeQuery(); 
                rs.next();
                id =rs.getInt(1);
                //return date set to null as there is no return date
                arrdate = null;
            }


        %>

           <!--division that will show information inserted to the user-->
        <div style='border: 1px solid black; position: relative; background-color: white; width: 45%;  height:480px; margin: 10% 28%; box-sizing: border-box;box-shadow: 0 15px 25px rgba(0,0,0,.6); border-radius: 10px;'> 

            <h2 style='text-align:center'>Your Flight Details</h2>
            <p style='text-align:center'><b>Flight ID:</b><%=id%></p>
            <p style='text-align:center'><b>First Name:</b><%=fname%></p>
            <p style='text-align:center'><b>Last Name:</b> <%=lname%></p>
            <p style='text-align:center'><b>Departure City:</b><%= depcity%></p>
            <p style='text-align:center'><b>Arrival City::</b> <%= arrcity%> </p>
            <p style='text-align:center'><b>Class:</b> <%= classes%></p>
            <p style='text-align:center'><b>Departure Date:</b><%= depdate%></p>
            <p style='text-align:center'><b>Return Date:</b> <%=arrdate%></p>
            <button style='text-align:center; color: white; padding:10px; margin:5% 35%; background-color: blue; width:30%; border-radius:40px; border:none '><a href="bookingFlightsForm.jsp" style="text-decoration:none; color:white">Back to Home Page </a></button> 
        </div>

        <%@ include file="FooterJsp.jsp" %>  
    </body>
</html>
